import { Request, Response, NextFunction } from "express";
import sanitizeHtml from "sanitize-html";

function deepSanitize(value: unknown): unknown {
  if (typeof value === "string") {
    return sanitizeHtml(value, { allowedTags: [], allowedAttributes: {} }).trim();
  }
  if (Array.isArray(value)) {
    return value.map(deepSanitize);
  }
  if (value && typeof value === "object") {
    const result: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(value)) {
      result[key] = deepSanitize(val);
    }
    return result;
  }
  return value;
}

export function sanitizeInput(req: Request, _res: Response, next: NextFunction) {
  // 1. Skip completely if the GraphQL payload is blank or is an Introspection Query from VS Code/Playground
if (req.body && typeof req.body.query === "string") {
  const queryStr = req.body.query.trim();
  if (queryStr === "" || queryStr.includes("__schema") || queryStr.includes("IntrospectionQuery")) {
    return next();
  }
}

  // 2. Sanitize req.body safely (plain objects generated by body-parser)
  if (req.body) {
    req.body = deepSanitize(req.body);
  }

  // 3. Clear and update req.query inline without breaking Express getters
  if (req.query && Object.keys(req.query).length > 0) {
    const sanitizedQuery = deepSanitize(req.query) as Record<string, any>;
    for (const key in req.query) {
      delete req.query[key];
    }
    Object.assign(req.query, sanitizedQuery);
  }

  // 4. Clear and update req.params inline without breaking Express getters
  if (req.params && Object.keys(req.params).length > 0) {
    const sanitizedParams = deepSanitize(req.params) as Record<string, any>;
    for (const key in req.params) {
      delete req.params[key];
    }
    Object.assign(req.params, sanitizedParams);
  }

  next();
}